### ISSUE TITLE
Importing issue from Jspych to Gorilla

### ISSUE THREAD

**Issue by keijiota** [jspsych/jsPsych#3218]
Hello jsPsych community, 

I have an issue where I import video-keyboard-response to Gorilla and play .mp4 file. I have the error message below. It seems this plugin does not recognize the file as recommended stimulus property. I run the same code on my local laptop without problem. I used to use image files and image-button-response on Gorilla. The problem might be 1) Gorilla cannot load mp4 file when I run it on code editor of Gorilla or 2) there is a safety issue on web browser which restricts me to play a video. 
Have you had any similar issue? 

Many thanks as always.
Keiji  

rollbar.min.js:1  Rollbar: Error: 
        The stimulus property for the video-keyboard-response plugin must be an array
        of files. See https://www.jspsych.org/latest/plugins/video-keyboard-response/#parameters
      
    at VideoKeyboardResponsePlugin.trial (plugin-video-keyboard-response.js:109:21)
    at JsPsych.doTrial (jspsych.js:3057:45)
    at JsPsych.nextTrial (jspsych.js:3000:18)
    at onExtensionCallbacksFinished (jspsych.js:2796:30)
    at JsPsych.finishTrial (jspsych.js:2821:17)
    at end_trial (plugin-preload.js:238:28)
    at on_success (plugin-preload.js:190:19)
    at file_loading_success (plugin-preload.js:337:19)
    at request.onload (jspsych.js:1007:25)
    at t._rollbar_wrapped.t._rollbar_wrapped (rollbar.min.js:1:20014)

**Comment by Shaobin-Jiang** [comment]
But it says here:

> The stimulus property for the video-keyboard-response plugin must be an array

Are you certain you have set the `stimulus` property properly?

**Comment by keijiota** [comment]
Thank you. I have solved the issue. I had to add [ ] to my stimulus when importing a mp4 file on Gorilla, which I did not need when I was working on my local computer. 
Thanks very much. 
Keiji
