### ISSUE TITLE
sPsych.endExperiment  not working

### ISSUE THREAD

**Issue by meirgf** [jspsych/jsPsych#3382]
I am using version 8.0.2
When trying to end an experment I get

8.0.2
Uncaught (in promise) TypeError: jsPsych.endExperiment is not a function
    at on_finish (a2.html?participantId=20240825_1&assignmentId=assnmnt123&projectId=proj123&part=1:236:16)
    at Trial.runParameterCallback (jspsych.js:2422:15)
    at Trial.onFinish (jspsych.js:2439:33)
    at async Trial.run (jspsych.js:2303:6)
    at async Timeline.run (jspsych.js:2581:16)
    at async JsPsych.run (jspsych.js:2837:6)

**Comment by jodeleeuw** [comment]
It was replaced by `abortExperiment()` in version 8.

**Comment by meirgf** [comment]
Thank you!

Works now…
